-- Basic
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")

-- Plugins
require("plugins.hop")
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.dashboard")
require("plugins.autopairs")
require("plugins.autotags")
require("plugins.bufferline")
require("plugins.comments")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.whichkey")
require("plugins.colorizer")
require("plugins.iconpicker")
